import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import entity.Client;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;

/**
 * Created by Кирилл on 13.04.2017.
 */
public class AddClient extends JFrame {
    private JPanel panel1;
    private JTextField id;
    private JTextField name;
    private JTextField phoneNumber;
    private JTextField birthDate;
    private JButton addClient;
    private Controller controller;

    public AddClient(final Controller controller) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        this.controller = controller;
        $$$setupUI$$$();
        setContentPane(panel1);
        pack();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Добавить клиента");
        addClient.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Client client = new Client();
//              client.setId(Integer.valueOf(id.getText()));
                client.setName(name.getText());
                client.setNumber(phoneNumber.getText());
                client.setBirthDate(Date.valueOf(birthDate.getText()));
                controller.getHibernate().add(client);

            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:11dlu:noGrow,center:d:noGrow,left:4dlu:noGrow,fill:229px:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("ФИО");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(3, 3));
        name = new JTextField();
        panel1.add(name, cc.xy(5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Номер телефона");
        panel1.add(label2, cc.xy(3, 5));
        phoneNumber = new JTextField();
        panel1.add(phoneNumber, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Дата рождения");
        panel1.add(label3, cc.xy(3, 7));
        birthDate = new JTextField();
        panel1.add(birthDate, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        addClient = new JButton();
        addClient.setText("Добавить");
        panel1.add(addClient, cc.xy(3, 9));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
