import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import entity.Item;
import entity.Nomenclature;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Created by Кирилл on 19.04.2017.
 */
public class AddItemToShip extends JFrame {
    private JPanel panel1;
    private JComboBox comboBox1;
    private JTextField textField1;
    private JButton add;
    private Controller controller;
    private ArrayList curItems;
    private ArrayList queryNom;
    private int storage;

    public AddItemToShip(Controller controller, ArrayList curItems, int storage) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        $$$setupUI$$$();
        this.controller = controller;
        setContentPane(panel1);
        pack();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Добавить заказ поставщику");
        this.controller = controller;
        this.curItems = curItems;
        this.storage = storage;
        initCombos();
        add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Item tmp = (Item) queryNom.get(comboBox1.getSelectedIndex());
                tmp.setQuanity(Integer.valueOf(textField1.getText()));
                tmp.setStorageId(storage);
                curItems.add(tmp);
            }
        });
    }

    private void initCombos() {
        queryNom = controller.getHibernate().get("Item");
        for (Object o : queryNom) {
            Item o1 = (Item) o;
            ArrayList nom = controller.getHibernate().get("Nomenclature where id=" + o1.getNomenclatureId());
            Nomenclature nomenclature = (Nomenclature) nom.get(0);
            comboBox1.addItem(nomenclature.getName());
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:269px:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("Номенклатура");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(1, 1));
        comboBox1 = new JComboBox();
        panel1.add(comboBox1, cc.xy(3, 1));
        final JLabel label2 = new JLabel();
        label2.setText("Количество");
        panel1.add(label2, cc.xy(1, 3));
        add = new JButton();
        add.setText("Добавить");
        panel1.add(add, cc.xy(3, 5));
        textField1 = new JTextField();
        panel1.add(textField1, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
