import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import entity.Client;
import entity.Item;
import entity.Nomenclature;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by Кирилл on 19.04.2017.
 */
public class AddItemToDeal extends JFrame {
    private Controller controller;
    private JPanel panel1;
    private JComboBox comboBox1;
    private JTextField textField1;
    private JButton addItem;
    private List curItems;
    private List curItemsQuery;

    public AddItemToDeal(Controller controller, List curItems) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        $$$setupUI$$$();
        this.controller = controller;
        this.curItems = curItems;
        initComboBox();
        setContentPane(panel1);
        pack();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Добавить товар в заказ");
        addItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Item item = (Item) curItemsQuery.get(comboBox1.getSelectedIndex());
                item.setQuanity(Integer.valueOf(textField1.getText()));
                curItems.add(item);
            }
        });
    }

    private void initComboBox() {
        curItemsQuery = controller.getHibernate().get("Item");
        for (Object o : curItemsQuery) {
            Item o1 = (Item) o;
            ArrayList nom = controller.getHibernate().get("Nomenclature where id=" + o1.getNomenclatureId());
            Nomenclature nomenclature = (Nomenclature) nom.get(0);
            comboBox1.addItem(nomenclature.getName());
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow"));
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:362px:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panel2.add(panel1, cc.xy(1, 1));
        final JLabel label1 = new JLabel();
        label1.setText("Товар");
        panel1.add(label1, cc.xy(3, 3));
        comboBox1 = new JComboBox();
        panel1.add(comboBox1, cc.xy(5, 3));
        final JLabel label2 = new JLabel();
        label2.setText("Количество");
        panel1.add(label2, cc.xy(3, 5));
        textField1 = new JTextField();
        panel1.add(textField1, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        addItem = new JButton();
        addItem.setText("Добавить");
        panel1.add(addItem, cc.xy(5, 7));
    }
}
