import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import entity.Nomenclature;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Кирилл on 14.04.2017.
 */
public class AddNomenclature extends JFrame {
    private JPanel panel1;
    private JTextField name;
    private JTextField article;
    private JTextField description;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JButton addPicture;
    private JButton save;
    private Controller controller;

    public AddNomenclature(final Controller controller) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        $$$setupUI$$$();
        setContentPane(panel1);
        pack();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Добавить номенклатуру");
        this.controller = controller;
        save.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Nomenclature o = new Nomenclature();
                o.setName(name.getText());
                o.setArticle(article.getText());
                o.setDescritrion(description.getText());
                o.setBasePrice(Double.valueOf(textField1.getText()));
                o.setWholesalePrice(Double.valueOf(textField2.getText()));
                o.setRetailPrice(Double.valueOf(textField3.getText()));
                controller.getHibernate().add(o);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow"));
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:11dlu:noGrow,center:d:noGrow,left:4dlu:noGrow,fill:229px:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panel2.add(panel1, cc.xy(1, 1));
        final JLabel label1 = new JLabel();
        label1.setText("Наименование");
        panel1.add(label1, cc.xy(3, 3));
        name = new JTextField();
        panel1.add(name, cc.xy(5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Артикул");
        panel1.add(label2, cc.xy(3, 5));
        article = new JTextField();
        panel1.add(article, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Описание");
        panel1.add(label3, cc.xy(3, 7));
        description = new JTextField();
        panel1.add(description, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label4 = new JLabel();
        label4.setText("Базовая цена");
        panel1.add(label4, cc.xy(3, 9));
        textField1 = new JTextField();
        panel1.add(textField1, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        label5.setText("Оптовая цена");
        panel1.add(label5, cc.xy(3, 11));
        textField2 = new JTextField();
        panel1.add(textField2, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label6 = new JLabel();
        label6.setText("Розничная цена");
        panel1.add(label6, cc.xy(3, 13));
        textField3 = new JTextField();
        panel1.add(textField3, cc.xy(5, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label7 = new JLabel();
        label7.setText("Изображение");
        panel1.add(label7, cc.xy(3, 15));
        addPicture = new JButton();
        addPicture.setText("Добавить");
        panel1.add(addPicture, cc.xy(5, 15));
        save = new JButton();
        save.setText("Сохранить");
        panel1.add(save, cc.xy(3, 17));
    }
}
