import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Кирилл on 19.04.2017.
 */
public class Login extends JFrame {
    private JPanel panel1;
    private JTextField hostName;
    private JTextField login;
    private JPasswordField password;
    private JButton connect;
    private JCheckBox defaultCheck;
    private JTextField dbName;
    private Controller controller;
    private Login form;

    public Login(Controller controller) {
        this.form = this;
        this.controller = controller;
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        $$$setupUI$$$();
        setContentPane(panel1);
        pack();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Вход в систему");
        connect.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    if (defaultCheck.isSelected()) {
                        controller.initModel();
                        controller.initView();
                        form.dispose();
                    } else {
                        controller.initModel(hostName.getText(), dbName.getText(), login.getText(), new String(password.getPassword()));
                        controller.initView();
                        form.dispose();
                    }
                } catch (Exception ex) {

                }
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("Имя хоста");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(3, 3));
        hostName = new JTextField();
        panel1.add(hostName, cc.xy(5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Логин");
        panel1.add(label2, cc.xy(3, 7));
        login = new JTextField();
        panel1.add(login, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Пароль");
        panel1.add(label3, cc.xy(3, 9));
        password = new JPasswordField();
        panel1.add(password, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        connect = new JButton();
        connect.setText("Подключиться");
        panel1.add(connect, cc.xy(5, 11));
        defaultCheck = new JCheckBox();
        defaultCheck.setText("Стандартное");
        panel1.add(defaultCheck, cc.xy(3, 11));
        final JLabel label4 = new JLabel();
        label4.setText("Название базы");
        panel1.add(label4, cc.xy(3, 5));
        dbName = new JTextField();
        panel1.add(dbName, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
